# Generated by Django 4.0.4 on 2022-05-09 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=127, verbose_name='ФИО')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='my_photo/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Обо мне',
                'verbose_name_plural': 'Обо мне',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='contacts_logo/', verbose_name='Лого соц. сети')),
                ('link', models.URLField(max_length=511, verbose_name='Ссылка на соц. сеть')),
                ('name', models.CharField(max_length=127, verbose_name='Название соц. сети')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('pre_description', models.CharField(max_length=127, verbose_name='Первоночальное описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='projects/', verbose_name='Картинка')),
                ('link', models.URLField(max_length=511, verbose_name='Ссылка на проект')),
                ('date_develop', models.CharField(max_length=127, verbose_name='Время разработки')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Название категории')),
                ('pre_description', models.CharField(max_length=127, verbose_name='Первоночальное описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='project_categories/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Категория проектов',
                'verbose_name_plural': 'Категории проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/carusel', verbose_name='Картинка')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Картинки проекта',
                'verbose_name_plural': 'Картинки проектов',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='mainapp.projectscategory', verbose_name='Категория'),
        ),
    ]
